
spring:
  # PostgreSQL DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

#  main:
#    allow-bean-definition-overriding: true

# Mybatis ??
mybatis:
  # default Package location - resultType? Alias? ?????.
  type-aliases-package: com.example.payroll.repository
  # mapper location - ?? ? xml ??? ?????.
  mapper-locations: classpath:mappers/*.xml
  # column name to camel case - ?? ?? ???? CamelCase? ?? ??? ???.
  configuration:
    map-underscore-to-camel-case: true

#target api for feign client test
external-api:
  http-bin: https://httpbin.org
#mybatis.config-location=classpath:mybatis-config.xml

