
spring:
  # PostgreSQL DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

#  main:
#    allow-bean-definition-overriding: true

# Mybatis ??
mybatis:
  # default Package location - resultType? Alias? ?????.
  type-aliases-package: com.example.payroll.repository
  # mapper location - ?? ? xml ??? ?????.
  mapper-locations: classpath:mappers/*.xml
  # column name to camel case - ?? ?? ???? CamelCase? ?? ??? ???.
  configuration:
    map-underscore-to-camel-case: true

#mybatis.config-location=classpath:mybatis-config.xml

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 5000
        loggerLevel: NONE
      simple-client:
        connectTimeout: 1000
        readTimeout: 4000
        loggerLevel: FULL
  demo:
    http-bin: https://httpbin.org

logging:
  level:
    com.example.payroll: DEBUG